from abc import ABC, abstractmethod
from typing import Any, Dict
from core.state_manager import StateManager

class BaseTool(ABC):
    """Abstract base class that all orchestrator tools must inherit from."""

    @classmethod
    @abstractmethod
    def get_name(cls) -> str:
        """Returns the unique string identifier for this tool (e.g., 'docmind')."""
        pass

    @classmethod
    @abstractmethod
    def get_description(cls) -> str:
        """Returns a clear description of what this tool does and what arguments it accepts.
        Used by the LLM Planner to figure out how to use the tool.
        """
        pass

    @abstractmethod
    def run(self, state: StateManager, args: Dict[str, Any]) -> bool:
        """
        Executes the tool's core logic.
        
        Args:
            state: The global StateManager for reading/writing shared context.
            args: A dictionary of arguments generated by the LLM Planner.
            
        Returns:
            True if execution was successful, False otherwise.
        """
        pass
